application: gigafoundationde 
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|svg))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|svg))

- url: .*
  script: main.py
